spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    tomcat:
      min-idle: 2
      max-active: 5
      initial-size: 5
      remove-abandoned: true

  jpa:
    hibernate:
      ddl-auto: update